import React from 'react'
import Dsa from './Dsa'

export const metadata = {
  title: "Data  Structures and Algorithms",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div className='pt-[7rem]'>
      <Dsa/>
    </div>
  )
}

export default page
